
const FaceTecStrings = {
  'FaceTec_accessibility_cancel_button': 'Cancel',

  'FaceTec_feedback_center_face': 'Center your face',
  'FaceTec_feedback_face_not_found': 'Keep your face in the oval',
  'FaceTec_feedback_move_away_web': 'Move your face farther',
  'FaceTec_feedback_move_phone_away': 'Move your face farther',
  'FaceTec_feedback_move_web_closer': 'Move closer',
  'FaceTec_feedback_move_phone_closer': 'Move closer',
  'FaceTec_feedback_move_to_eye_level_web': 'Move camera to eye level',
  'FaceTec_feedback_move_phone_to_eye_level': 'Move camera to eye level',
  'FaceTec_feedback_face_not_looking_straight_ahead': 'Look at the camera',
  'FaceTec_feedback_face_not_upright': 'Look straight ahead',
  'FaceTec_feedback_face_not_upright_mobile': 'Look straight ahead',
  'FaceTec_feedback_hold_steady': 'Stay still',
  'FaceTec_feedback_move_web_even_closer': 'Even closer',
  'FaceTec_feedback_use_even_lighting': 'Light face more evenly',

  'FaceTec_instructions_header_ready_desktop': 'Get Ready For Your Video Selfie',
  'FaceTec_instructions_message_ready_desktop': 'Frame your face in the oval and press I\'m ready',
  'FaceTec_instructions_header_ready_1_mobile': 'Let\'s get going',
  'FaceTec_instructions_header_ready_2_mobile': '',
  'FaceTec_instructions_message_ready_1_mobile': 'Frame your face in the oval and',
  'FaceTec_instructions_message_ready_2_mobile': 'press I\'m ready',

  'FaceTec_action_im_ready': 'START',
  'FaceTec_presession_frame_your_face': 'Keep your face in the oval',
  'FaceTec_presession_look_straight_ahead': 'Look straight ahead',
  'FaceTec_presession_hold_steady3': 'Stay still: 3',
  'FaceTec_presession_hold_steady2': 'Stay still: 2',
  'FaceTec_presession_hold_steady1': 'Stay still: 1',
  'FaceTec_presession_eyes_straight_ahead': 'Look straight ahead',
  'FaceTec_presession_remove_dark_glasses': 'Remove dark glasses',
  'FaceTec_presession_neutral_expression': 'Neutral expression, no smiling',
  'FaceTec_presession_conditions_too_bright': 'Conditions too bright',
  'FaceTec_presession_brighten_your_environment': 'Brighten your environment',

  'FaceTec_result_facescan_upload_message': 'Checking',
  'FaceTec_result_idscan_upload_message': 'Checking',

  'FaceTec_retry_header': 'Let\'s try that again',
  'FaceTec_retry_subheader_message': 'We couldn\'t capture your face.',
  'FaceTec_retry_your_image_label': 'Your selfie',
  'FaceTec_retry_ideal_image_label': 'Ideal selfie',
  'FaceTec_retry_instruction_message_1': 'Great smile, but keep a straight face',
  'FaceTec_retry_instruction_message_2': 'Watch out for poor lighting and blur',
  'FaceTec_retry_instruction_message_3': 'That was too blury',
  'FaceTec_action_try_again': 'TRY AGAIN',

  'FaceTec_camera_feed_issue_header': '<b>Issue Encrypting Camera Feed</b>',
  'FaceTec_camera_feed_issue_subheader_message': 'This system cannot be verified due to the following:',
  'FaceTec_camera_feed_issue_table_header_1': 'Possible Issue',
  'FaceTec_camera_feed_issue_table_header_2': 'Fix',
  'FaceTec_camera_feed_issue_table_row_1_cell_1_firefox_permissions_error': 'Camera permissions not remembered in Firefox.',
  'FaceTec_camera_feed_issue_table_row_1_cell_2_firefox_permissions_error': 'Check Remember Permissions.',
  'FaceTec_camera_feed_issue_table_row_1_cell_1': 'Camera already in use by another App.',
  'FaceTec_camera_feed_issue_table_row_1_cell_2': 'Close the other App.',
  'FaceTec_camera_feed_issue_table_row_2_cell_1': 'A 3rd-Party App is modifying the video.',
  'FaceTec_camera_feed_issue_table_row_2_cell_2': 'Close/Uninstall the other App.',
  'FaceTec_camera_feed_issue_table_row_3_cell_1': 'Hardware not capable of being secured.',
  'FaceTec_camera_feed_issue_table_row_3_cell_2': 'Use a different Device.',
  'FaceTec_camera_feed_issue_subtable_message': 'This App blocks suspicious webcam configurations. <a href=\'https://livenesscheckhelp.com/\' target=\'_blank\' style=\'text-decoration:underline; pointer-events:all;\'>Learn More Here</a>.',
  'FaceTec_camera_feed_issue_action': 'Try Again Anyway',
  'FaceTec_camera_feed_issue_action_firefox_permissions_error': 'OK',

  'FaceTec_camera_permission_header': 'Enable Camera',
  'FaceTec_camera_permission_message': 'Camera permissions disabled.<br/>Please check your operating system and browser settings.',
  'FaceTec_action_ok': 'OK',

  'FaceTec_enter_fullscreen_header': 'Full Screen Selfie Mode',
  'FaceTec_enter_fullscreen_message': 'Before we begin, please click the button below to open full screen mode',
  'FaceTec_enter_fullscreen_action': 'Open Full Screen',

  'FaceTec_initializing_camera': 'Loading',
  'FaceTec_initializing_camera_still_loading': 'Loading',

  'FaceTec_idscan_type_selection_header': 'Please Select Your<br/>ID Document Type',
  'FaceTec_action_select_id_card': 'PHOTO ID',
  'FaceTec_action_select_passport': 'PASSPORT',
  'FaceTec_idscan_capture_id_card_front_instruction_message': 'Show Front of Photo ID',
  'FaceTec_idscan_capture_id_card_back_instruction_message': 'Show Back of Photo ID',
  'FaceTec_idscan_capture_passport_instruction_message': 'Show Passport Photo Page',
  'FaceTec_action_take_photo': 'TAKE PHOTO',
  'FaceTec_idscan_review_id_card_front_instruction_message': 'Confirm Photo is Clear & Legible',
  'FaceTec_idscan_review_id_card_back_instruction_message': 'Confirm Photo is Clear & Legible',
  'FaceTec_idscan_review_passport_instruction_message': 'Confirm Photo is Clear & Legible',
  'FaceTec_action_accept_photo': 'ACCEPT',
  'FaceTec_action_retake_photo': 'RETAKE',

  'FaceTec_result_idscan_unsuccess_message': 'ID Photo<br/>Did Not Match<br>User\'s Face',

  'FaceTec_result_success_message': 'Selfie done'
};

export default FaceTecStrings;
